# -*- coding: utf-8 -*-

trade_union = {}

# rmt
trade_union['Rail, Maritime and Transport Workers'] = 'RMT'
trade_union['RMT Trade Union'] = 'RMT'
trade_union['RMT NE Region'] = 'RMT'
trade_union['RMT Head Office'] = 'RMT'
trade_union['RMT Manchester South'] = 'RMT'
trade_union['Rail, Maritime and Transport Union'] = 'RMT'
trade_union['RMT Union'] = 'RMT'
trade_union['RMT'] = 'RMT'
trade_union['The National Union of Rail, Maritime and Transport Workers'] = 'RMT'

# unite
trade_union['Unite the Union'] = 'UNITE'
trade_union['Unite the union'] = 'UNITE'
trade_union['Unite Union'] = 'UNITE'
trade_union['Unite'] = 'UNITE'
trade_union['Unite (Northeast, Yorkshire and Humberside)'] = 'UNITE'
trade_union['Unite the Union Vauxhall Motors'] = 'UNITE'
trade_union['Unite the Union (Rochdale Branch)'] = 'UNITE'
trade_union['Vauxhall Motors Unite Shop Stewards Committee'] = 'UNITE'
trade_union['UNITE'] = 'UNITE'
trade_union[' Unite the Union'] = 'UNITE'
trade_union['Unite The Union'] = 'UNITE'

# gmb
trade_union['GMB Northern'] = 'GMB'
trade_union['GMB Northern Region'] = 'GMB'
trade_union['GMB'] = 'GMB'
trade_union['GMB National Office'] = 'GMB'
trade_union['GMB Birmingham and West Midlands'] = 'GMB'
trade_union['GMB Wales and the South West'] = 'GMB'
trade_union['GMB Midland and the East Coast'] = 'GMB'
trade_union['GMB Southern Region'] = 'GMB'
trade_union['GMB North West & Irish Region'] = 'GMB'
trade_union['GMB London Region'] = 'GMB'
trade_union['GMB Yorkshire and North Derbyshire'] = 'GMB'
trade_union['GMB Yorkshire Region and National'] = 'GMB'
trade_union['GMB Midland & East Coast Region'] = 'GMB'
trade_union['GMB - Southern Region'] = 'GMB'
trade_union['GMB Southern Union'] = 'GMB'
trade_union['GMB NW & Irish Region'] = 'GMB'
trade_union['GMB Midland and East Coast Region'] = 'GMB'
trade_union['GMB Yorkshire and North Derbyshire Region'] = 'GMB'
trade_union['GMB North West and Irish Region'] = 'GMB'
trade_union['GMB North West Region'] = 'GMB'
trade_union['GMB Union'] = 'GMB'
trade_union['GMB Trade Union'] = 'GMB'
trade_union['GMB Wales & South West'] = 'GMB'
trade_union['GMB Wales'] = 'GMB'

# cwu
trade_union['CWU'] = 'CWU'
trade_union['Communication Workers Union North East Region'] = 'CWU'
trade_union['Communication Workers Union York and District Branch'] = 'CWU'
trade_union['Communication Workers Union Wales and Marches'] = 'CWU'
trade_union['Communication Workers Union'] = 'CWU'
trade_union['Communications Workers Union, Wales and Marches Region'] = 'CWU'
trade_union['CWU North West'] = 'CWU'
trade_union['Communication Workers Union Midlands Region'] = 'CWU'
trade_union["Communication Workers' Union"] = 'CWU'
trade_union['CWU Gloucester'] = 'CWU'
trade_union['CWU Bristol'] = 'CWU'
trade_union['Communication Workers Union - Eastern Region'] = 'CWU'
trade_union['CWU Midlands Region'] = 'CWU'
trade_union['Communications Workers Union'] = 'CWU'
trade_union['Communication Workers Union (CWU)'] = 'CWU'
trade_union['Communication Workers Union North West Region'] = 'CWU'
trade_union['Communications Workers Union, Wales and the Marches'] = 'CWU'
trade_union['Communication Workers Union Northern Region'] = 'CWU'
trade_union[' CWU'] = 'CWU'
trade_union['Communication Workers Union North West'] = 'CWU'
trade_union[u'Communication Workers’ Union North East Region,'] = 'CWU'
trade_union['Communications Workers Union (CWU)'] = 'CWU'

# unison
trade_union['UNISON'] = 'UNISON'
trade_union['Unison'] = 'UNISON'
trade_union['UNISON Cymru/Wales'] = 'UNISON'
trade_union['Unison North West'] = 'UNISON'
trade_union['UNISON Labour Link'] = 'UNISON'
trade_union['UNISON South West'] = 'UNISON'
trade_union['UNISON Yorkshire & Humber Region'] = 'UNISON'
trade_union['UNISON East Midlands'] = 'UNISON'
trade_union['UNISON - East Midlands'] = 'UNISON'
trade_union['Unison centre'] = 'UNISON'
trade_union['UNISON SE'] = 'UNISON'
trade_union['UNISON South East'] = 'UNISON'

# others
trade_union['FBU'] = 'FBU'
trade_union['Fire Brigades Union'] = 'FBU'
trade_union['Fire Brigades Union (FBU)']  = 'FBU'

trade_union["Transport Salaried Staffs' Association"] = 'TSSA'
trade_union['TSSA 2012'] = 'TSSA'
trade_union['TSSA'] = 'TSSA'
trade_union['TSSA Union'] = 'TSSA'
trade_union['Transport and Salaried Staffs Association'] = 'TSSA'

trade_union['Community'] = 'COMMUNITY UNION'
trade_union['Community Union'] = 'COMMUNITY UNION'
trade_union['Community the Union'] = 'COMMUNITY UNION'
trade_union['Community Trade Union'] = 'COMMUNITY UNION'

trade_union["Musicians' Union"] = 'MUSICIANS UNION'
trade_union['Musicians Union'] = 'MUSICIANS UNION'
trade_union["The Musicians' Union"] = 'MUSICIANS UNION'

trade_union['Public and Commercial Services Union'] = 'PCS'
trade_union['Public and Commercial Services Union (PCS)'] = 'PCS'

trade_union['ASLEF'] = 'ASLEF'
trade_union['USDAW'] = 'USDAW'
trade_union['USDAW Union'] = 'USDAW'
trade_union['USDAW Trade Union'] = 'USDAW'
trade_union['BWTUC'] = 'BWTUC'
trade_union['Bakers and Allied Food Workers Union'] = 'BAKERS UNION'
trade_union['National Union of Journalists (NUJ)'] = 'NUJ'
trade_union['Union of Shop, Distributive and Allied Workers'] = 'SHOP UNION'
trade_union['Union of Shop, Allied and Distributive Workers'] = 'SHOP UNION'

trade_union['The Prison Officers Association'] = 'POA'
trade_union['NAPO - the Probation and Family Courts Union'] = 'NAPO'

